travis:
  secure:
    BINSTAR_TOKEN: hXSYH/JkiC4YrNNhiCaWvynyuZjAveocBV2aYhgDTMHqHEqpGg/SiGRdcUtsXEvFsi3T+61REzHJKyn2U6v+PXLQZTJxCqqm/1a5bsT+h392Tvz9dpPm/rrbwVLmrioEeDHt0CAm+mz8ush/e9W4Qsr4X4l+X+yT/bMbX2hgeakrEBFcZBOoTTRwkn8MQ87SJp64rIlI/Zjl98czhNJSLbAA9i0LPLmpgjMUSL3ML6OeacnpyxOE7piDu4b8VCtUjlcwD3GTMIVDvW91i6s1dK/pMSTeP/wVuiNsHabZqZpDZmHQHcaGLh+kO9HepcSZ9CCNWurtv7Ia3HhIP08KaBacRA20oerPkx8vvbgsKVXyvBv6Re0NJEc5apj5NUsyrP/3ewgbiBMAjmZMnACTF3EYhXSNVZW3kMFi1fj2JVeDeX7yIXIb9yoyF8+q+ObdwqNP+ubxR890vdo3ACHg/Tc4ZjhPkUKmASqV3jyneJgxi856UynLZh9hlkqPO47nu/Ip8i9gaLgmRfbwTEArm8eFN7xQIjzRRjrQND8/x/bmf617MNWe9MTdA3762U8AvRvYirGTAv4hgtEVfV1Qp0Vi0W0o7rJzHa8PD4pXDLNrlwxRVPTK2MzBFPdMFVZ37rKuKvJ5BSwWXVisDMIYozSNQoKKkAeH8I0X+GdOTbA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
